import type { Metadata } from "next";
import localFont from "next/font/local";
import { ColorModeScript, UIProvider } from "@yamada-ui/react";
import "./globals.css";
import Header from "@components/header";
import { serverApiClient } from "@lib/server-api-client";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isLoggedIn = await serverApiClient.isLoggedIn()

  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable}`}>
				<ColorModeScript
          type="cookie"
          nonce="testing"
        />
        <UIProvider>
					<Header isLoggedIn={isLoggedIn} />
					{children}
				</UIProvider>
      </body>
    </html>
  );
}
