import type { Metadata } from "next";
import localFont from "next/font/local";
import { ColorModeScript, UIProvider } from "@packages/ui";
import "./globals.css";
import Header from "./components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable}`}>
				<ColorModeScript
          type="cookie"
          nonce="testing"
        />
        <UIProvider>
					<Header />
					{children}
				</UIProvider>
      </body>
    </html>
  );
}
